### ISSUE TITLE
Pass environment variables into Docker

### ISSUE THREAD

**Issue by liyishuai** [coq-community/docker-coq-action#23]
I want to set `OPAMWITHTEST=true` to perform [`run-test`](https://opam.ocaml.org/doc/Manual.html#opamfield-run-test), but cannot do it with [GitHub Actions' `env`](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#about-environment-variables), because that parameter should be passed into Docker.

**Comment by liyishuai** [comment]
and `OPAMYES` should always be set to `true` for CI.

**Comment by erikmd** [comment]
OK so I did some experiments, to summarize:

the GitHub Actions YAML syntax wouldn't support putting an `env` map in the docker-coq-action options:

https://github.com/erikmd/docker-coq-github-action-demo/actions/runs/166741107

However a working solution would consist in putting one such `env` map in one level above, and adding an option telling which variables to export within the Docker context:

```yaml
  - uses: coq-community/docker-coq-action@todo
    with:
      opam_file: 'folder/coq-proj.opam'
      coq_version: ${{ matrix.coq_version }}
      ocaml_version: ${{ matrix.ocaml_version }}
      export_vars: 'VARIABLE OPAMWITHTEST'  # space-separated list of variables
    env:
      VARIABLE: 'some value'
      OPAMWITHTEST: 'true'
```

I didn't implement this fully yet, but would this syntax look good to you @liyishuai @Zimmi48 ?
