### ISSUE TITLE
opam_file should not be mandatory

### ISSUE THREAD

**Issue by JasonGross** [coq-community/docker-coq-action#26]
It doesn't seem necessary, and I'd rather not be forced to pass a dummy string / create a dummy opam file.

**Comment by Zimmi48** [comment]
Another solution would be for the default script to look for a unique `*.opam` file at the root of the repository if this variable is not provided. This would mean that the simplest possible CI configuration would become just:

```yml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
```

WDYT @erikmd?
