### ISSUE TITLE
Wish: Add e2e tests directly in docker-coq-action repo to automate validation(?)

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq-action#46]
but ideally without adding Coq/opam files in this repo… e.g.:

```yaml
[…]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'erikmd/docker-coq-github-actions-demo'
          ref: 'master'
      - uses: coq-community/docker-coq-action@master
        with:
          opam_file: 'coq-demo.opam'
          custom_image: 'coqorg/coq:dev'
```
