### ISSUE TITLE
docs: Mention the typical header of build.yml

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq-action#67]
We should probably document in the README that a standard phrasing for `.github/workflows/build.yml` is:

```yml
name: Docker-Coq CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    (…)
```
