### ISSUE TITLE
Inconsistency with Opam repository?

### ISSUE THREAD

**Issue by jwiegley** [coq-community/docker-coq-action#76]
I run this action against a projects that installs just fine locally with `opam install .`, but via CI fails with this error:
```
Error:  Package conflict!
    * Missing dependency:
      - coq-pact-model -> coq-hammer-tactics >= 1.3.2 -> coq < 8.11~
      not available because the package is pinned to version 8.15.2
    * Missing dependency:
      - coq-pact-model -> coq-hammer-tactics >= 1.3.2 -> coq < 8.12~
      not available because the package is pinned to version 8.15.2
    * Missing dependency:
      - coq-pact-model -> coq-hammer-tactics >= 1.3.2 -> coq < 8.13~
      not available because the package is pinned to version 8.15.2
    * Missing dependency:
      - coq-pact-model -> coq-hammer-tactics >= 1.3.2 -> coq < 8.14~
      not available because the package is pinned to version 8.15.2
    * Missing dependency:
      - coq-pact-model -> coq-hammer-tactics >= 1.3.2 -> coq < 8.15~
      not available because the package is pinned to version 8.15.2
```

My `ci.yml` file is:
```
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.16'
          - '8.15'
          - '8.14'
          - dev
        ocaml_version: ['default']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-pact-model.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
```

And my opam file is:
```
opam-version: "2.0"
maintainer: "johnw@newartisans.com"

homepage: "https://github.com/jwiegley/pact-model"
dev-repo: "git+https://github.com/jwiegley/pact-model.git"
bug-reports: "https://github.com/jwiegley/pact-model/issues"
license: "BSD-3-Clause"

synopsis: "Formal model of the Pact Smart Contracts language"
description: """
Formal model of the Pact Smart Contracts language.
"""

build: [make "-j%{jobs}%" ]
install: [make "install"]
depends: [
  "coq" {(>= "8.14" & < "8.17~") | (= "dev")}
  "coq-equations" {(>= "1.2" & < "1.4~") | (= "dev")}
  "coq-hammer" {(>= "1.3.2") | (= "dev")}
  "coq-hammer-tactics" {(>= "1.3.2") | (= "dev")}
  "coq-haskell" {(>= "1.1") | (= "dev")}
  "coq-category-theory" {(>= "1.0") | (= "dev")}
]

tags: [
]
authors: [
  "John Wiegley"
]
```

I've confirmed in the Coq Package List that `coq-hammer` has a version `1.3.2+8.15` that works fine with my build, but for some reason docker-coq-action doesn't see it as available?

**Comment by Blaisorblade** [comment]
The error is not too helpful, but coq-hammer and the default OCaml version aren't compatible; `coq-hammer` requires `ocaml >= 4.08`.

How I did the troubleshooting:

Found the actual logs are at https://github.com/kadena-io/pact-model/runs/7483595150?check_suite_focus=true and https://github.com/kadena-io/pact-model/runs/7483595177?check_suite_focus=true, and confirmed `opam update` was run correctly.

Pinning the package locally worked fine, so I tried replicating what happened in the image, then tried to install dependencies by hand, and finally got a useful error:

```
host$ docker run -it coqorg/coq:8.15
coq@719592caa6f7:~$ opam update
[...]
coq@719592caa6f7:~$ opam pin https://github.com/kadena-io/pact-model.git
Package coq-pact-model does not exist, create as a NEW package? [Y/n] y
coq-pact-model is now pinned to git+https://github.com/kadena-io/pact-model.git (version ~dev)

[ERROR] Package conflict!
  * Missing dependency:
    - coq-pact-model -> coq-hammer >= 1.3.2 -> coq < 8.11~
    not available because the package is pinned to version 8.15.2
  * Missing dependency:
    - coq-pact-model -> coq-hammer >= 1.3.2 -> coq < 8.12~
    not available because the package is pinned to version 8.15.2
  * Missing dependency:
    - coq-pact-model -> coq-hammer >= 1.3.2 -> coq < 8.13~
    not available because the package is pinned to version 8.15.2
  * Missing dependency:
    - coq-pact-model -> coq-hammer >= 1.3.2 -> coq < 8.14~
    not available because the package is pinned to version 8.15.2
  * Missing dependency:
    - coq-pact-model -> coq-hammer >= 1.3.2 -> coq < 8.15~
    not available because the package is pinned to version 8.15.2

[NOTE] Pinning command successful, but your installed packages may be out of sync.
coq@719592caa6f7:~$ opam install coq-hammer.1.3.2+8.15
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) -> ocaml-variants = 4.07.1+flambda -> ocaml = 4.07.1
    - coq-hammer >= 1.3.2+8.15 -> ocaml >= 4.08
    You can temporarily relax the switch invariant with `--update-invariant'

No solution found, exiting
```

**Comment by erikmd** [comment]
Hi!

thanks a lot @Blaisorblade for your troubleshooting!

So FYI @jwiegley, you can just change the [`ocaml_version`](https://github.com/coq-community/docker-coq-action#ocaml_version) after taking a look at the [list of supported versions](https://github.com/coq-community/docker-coq/wiki#ocaml-versions-policy), e.g.:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.16'
          - '8.15'
          - '8.14'
          - dev
        ocaml_version: ['4.14-flambda']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-pact-model.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
```
